runner:
  general:
    dry_run: false

  pred_thresholds:
    title_thresh: 99
    desc_thresh: 90

  folders:
    cache: data
    tatort_store_prefix: ""
    final: '1-new'#'0-fertig'
    output: '1-new'
    error: '2-check'

  mediathek:
    query_size: 100

sheduler:
  null