runner:
  general:
    dry_run: false

  pred_thresholds:
    title_thresh: 90
    desc_thresh: 80

  folders:
    cache: data
    tatort_store_prefix: ""
    final: /run/user/1000/gvfs/sftp:host=xu4,user=sheid/home/sheid/Tatort/0-fertig
    output: 1.1-new
    error: 1.2-check

  mediathek:
    query_size: 1000

sheduler:
  null